/*
vts_parsing: rust parser for the VTS and VTM (including others) files generated by VTOL VR.
Copyright (C) 2024 BlockListed

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/


pub mod parse;
pub mod unparse;

pub use parse::{parse, Value, Node, Float};
pub use unparse::unparse;

#[cfg(test)]
mod testing {
    const TEST_STR: &str = include_str!("../amogus testing.vts");

    #[test]
    fn full_test() {
        let left = TEST_STR;
        let right = &super::unparse(&super::parse(TEST_STR));
        eprintln!("{right}");
        assert_eq!(left, right);
    }
}
